version: '3.8'

services:
    mysql-container:
        image: mysql:latest
        container_name: c1
        ports:
          - "3306:3306"
        volumes:
          - ./mysql-datastore:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb